-- Adds durable observability for API-Football-only live sync runs.

CREATE TABLE IF NOT EXISTS public.live_sync_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL DEFAULT 'api-football',
  run_date date NOT NULL,
  timezone text NOT NULL DEFAULT 'Africa/Douala',
  ok boolean NOT NULL DEFAULT false,
  total_fixtures integer NOT NULL DEFAULT 0,
  tracked_fixtures integer NOT NULL DEFAULT 0,
  live_fixtures integer NOT NULL DEFAULT 0,
  finished_fixtures integer NOT NULL DEFAULT 0,
  sources jsonb NOT NULL DEFAULT '[]'::jsonb,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  diagnostic jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz NOT NULL DEFAULT now(),
  duration_ms integer NOT NULL DEFAULT 0
);

ALTER TABLE public.live_sync_runs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'live_sync_runs'
      AND policyname = 'live_sync_runs_service_role'
  ) THEN
    CREATE POLICY "live_sync_runs_service_role"
      ON public.live_sync_runs
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DROP POLICY IF EXISTS "live_sync_runs_select_all" ON public.live_sync_runs;
REVOKE ALL ON public.live_sync_runs FROM anon;
REVOKE ALL ON public.live_sync_runs FROM authenticated;
GRANT ALL ON public.live_sync_runs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.live_sync_runs_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS idx_live_sync_runs_finished_at
  ON public.live_sync_runs (finished_at DESC);

CREATE INDEX IF NOT EXISTS idx_live_sync_runs_provider_ok_finished_at
  ON public.live_sync_runs (provider, ok, finished_at DESC);

CREATE INDEX IF NOT EXISTS idx_live_sync_runs_errors_gin
  ON public.live_sync_runs USING gin (errors);

CREATE OR REPLACE FUNCTION public.get_live_data_health()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH latest_run AS (
    SELECT *
    FROM public.live_sync_runs
    ORDER BY finished_at DESC
    LIMIT 1
  ),
  latest_success AS (
    SELECT finished_at
    FROM public.live_sync_runs
    WHERE ok
    ORDER BY finished_at DESC
    LIMIT 1
  )
  SELECT jsonb_build_object(
    'provider', 'api-football',
    'latest_sync_at', (SELECT finished_at FROM latest_run),
    'latest_success_at', (SELECT finished_at FROM latest_success),
    'last_error', (
      SELECT CASE
        WHEN jsonb_array_length(errors) > 0 THEN errors
        ELSE NULL
      END
      FROM latest_run
    ),
    'source_counts', COALESCE((SELECT sources FROM latest_run), '[]'::jsonb),
    'last_diagnostic', COALESCE((SELECT diagnostic FROM latest_run), '{}'::jsonb),
    'last_total_fixtures', COALESCE((SELECT total_fixtures FROM latest_run), 0),
    'last_tracked_fixtures', COALESCE((SELECT tracked_fixtures FROM latest_run), 0),
    'last_live_fixtures', COALESCE((SELECT live_fixtures FROM latest_run), 0),
    'last_finished_fixtures', COALESCE((SELECT finished_fixtures FROM latest_run), 0),
    'active_matches', (
      SELECT count(*)
      FROM public.live_match_states
      WHERE status IN ('1H', '2H', 'HT', 'ET', 'P', 'BT', 'INT', 'LIVE', 'SUSP')
    ),
    'stale_active_matches', (
      SELECT count(*)
      FROM public.live_match_states
      WHERE status IN ('1H', '2H', 'HT', 'ET', 'P', 'BT', 'INT', 'LIVE', 'SUSP')
        AND updated_at < now() - interval '45 seconds'
    ),
    'finished_recent', (
      SELECT count(*)
      FROM public.live_match_states
      WHERE status IN ('FT', 'AET', 'PEN', 'AWD', 'WO')
        AND updated_at >= now() - interval '24 hours'
    ),
    'latest_state_update_at', (
      SELECT max(updated_at)
      FROM public.live_match_states
    ),
    'recent_events', (
      SELECT count(*)
      FROM public.live_match_events
      WHERE detected_at >= now() - interval '30 minutes'
    ),
    'recent_proxy_calls', (
      SELECT count(*)
      FROM public.api_usage_logs
      WHERE endpoint LIKE 'api-football/%'
        AND created_at >= now() - interval '30 minutes'
    ),
    'recent_sync_runs', (
      SELECT count(*)
      FROM public.live_sync_runs
      WHERE finished_at >= now() - interval '30 minutes'
    )
  );
$$;

GRANT EXECUTE ON FUNCTION public.get_live_data_health() TO anon;
GRANT EXECUTE ON FUNCTION public.get_live_data_health() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_live_data_health() TO service_role;
